sudo: false
language: cpp
compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls

install:
  - CXXFLAGS="-fprofile-arcs -ftest-coverage" make

script:
  - make test

after_success:
  - coveralls --exclude googletest --exclude ".*_unittest.cc" --gcov-options '\-lp'
  - bash <(curl -s https://codecov.io/bash) -t e0b40fda-ac03-4859-99c5-189c71710036 -X gcov
